<?php
/* --------------------------------------------------------------------*
 * Flussu v4.1.0 - Mille Isole SRL - Released under Apache License 2.0
 * --------------------------------------------------------------------*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * --------------------------------------------------------------------*
 * CLASS-NAME:       Flussu API Controller
 * UPDATED DATE:     04.08.2022 - Aldus - Flussu v2.8
 * VERSION REL.:     4.1.0 20250113 
 * UPDATE DATE:      12.01:2025 
 * -------------------------------------------------------*/
namespace Flussu\Controller;

use Dompdf\Dompdf;
use Dompdf\Options;
use Flussu\General;
use Flussu\Flussuserver\Command;

/**
 * This class is responsible for handling PDF printing functionality.
 * - It uses the Dompdf library to generate PDF documents.
 * - The main method is printToTempFilename(), which takes the title, data to be printed, header, and footer as parameters and returns the path of the generated PDF file.
 * - The printHtmlPageToTempFilename() method is used to print HTML text directly to a PDF file.
 * - The pippo() method is not used and can be removed.
 */

/**
 * Summary of PdfController
 */
class PdfController 
{

    /**
     * Summary of printToTempFilename
     * @param mixed $theData2BePrinted
     * @return string
     */
    public function printToTempFilename($title,$theData2BePrinted,$theHeader="",$theFooter=""){
        $AA=$_SERVER["DOCUMENT_ROOT"];
        $tr=substr($AA,0,strrpos($AA,"/")).$_ENV['tempdir'];
        $tmpfname = tempnam($tr, "F302");
        unlink($tmpfname);
        $tmpfname.= ".pdf";
        
        $options = new Options();
        $options->set('defaultMediaType', 'all');
        $options->set('isFontSubsettingEnabled', true);
        $options->set('tempdir', $tr);
        $options->set('isPhpEnabled', true);
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isRemoteEnabled', true);   

        $dompdf = new Dompdf($options);

        $questoAnno=date("Y");

        if (empty(trim($theFooter)))
            $theFooter="Flussu Service - www.flussu.com - Copyright(C)2021-".$questoAnno." Mille Isole SRL - www.milleisole.com";
        if (empty(trim($theHeader)))
            $theHeader="Document generated by Flussu - www.flussu.com";
        if (empty(trim($title)))
            $title="Flussu - document generator";

        $theHtml="<html><head>
        <title>".$title."</title>
        <meta name='description' content='Document from flussu'>
        <meta name='author' content='Flussu Service - www.flussu.com'>
        <style>
        @font-face {
            font-family: 'OpenSans';
            font-style: normal;
            font-weight: 400;
            font-stretch: 100%;
            font-display: swap;
            src: url(https://fonts.gstatic.com/s/opensans/v35/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjZ0B4gaVI.woff2) format('woff2');
            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;        
        }
        @font-face {
            font-family: 'OpenSans-Bold';
            font-style: normal;
            font-weight: 700;
            font-stretch: 100%;
            font-display: swap;
            src: url(https://fonts.gstatic.com/s/opensans/v35/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-muw.woff2) format('woff2');
            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
        }
        body{
            font-family: 'OpenSans';
            font-size.0.85em;
        }
        @page{
            margin-top: 120px;
            margin-bottom: 100px;
        }
        header{
            position: fixed;
            left: 0px;
            top: 0px;
            right: 0px;
            height: 120px;
            margin-top: -100px;
        }
        footer{
            position: fixed;
            left: 0px;
            right: 0px;
            height: 50px;
            bottom: 0px;
            margin-bottom: -40px;
        }
        inpage{
            page-break-inside:avoid;
        }
        hr{
            /*border-bottom:dotted 1px #303030;*/
        }
        </style></head>
        <body>
        <header>".Command::htmlSanitize($theHeader)."<br>&nbsp;<div style='border-bottom:solid 1px #252525'>&nbsp;</div></header>
        <footer style='font-size:0.8em'>&nbsp;<br><div style='border-top:solid 1px #252525'>&nbsp;</div><br><center>".Command::htmlSanitize($theFooter)."</center></footer>
        <div style='margin-left:2em;margin-right:2em'>".Command::htmlSanitize($theData2BePrinted)."</div>";
        
        /*
        $theHtml.=str_replace("£","$","
        <script type='text/php'>

        if ( isset(£pdf) ) {
        
          £size = 6;
          £color = array(0,0,0);
          if (class_exists('Font_Metrics')) {
            £font = Font_Metrics::get_font('OpenSans');
            £text_height = Font_Metrics::get_font_height(£font, £size);
            £width = Font_Metrics::get_text_width('Page 1 of 2', £font, £size);
          } elseif (class_exists('Dompdf\\FontMetrics')) {
            £font = £fontMetrics->getFont('OpenSans');
            £text_height = £fontMetrics->getFontHeight(£font, £size);
            £width = £fontMetrics->getTextWidth('Page 1 of 2', £font, £size);
          }
        
          £foot = £pdf->open_object();
          
          £w = £pdf->get_width();
          £h = £pdf->get_height();
        
          // Draw a line along the bottom
          £y = £h - £text_height - 24;
          £pdf->line(16, £y, £w - 16, £y, £color, 0.5);
        
          £pdf->close_object();
          £pdf->add_object(£foot, 'all');
        
          £text = 'Page {PAGE_NUM} of {PAGE_COUNT}';  
        
          // Center the text
          £pdf->page_text(£w / 2 - £width / 2, £y, £text, £font, £size, £color);
          
        }
        </script>
        ");*/
        
        $theHtml=str_replace("style='font-size:1.2em;font-weight:800' ","style='font-size:.95em;font-weight:700' ",$theHtml)."</body></html>";
        //$theHtml=str_replace("\'","&apos;",$theHtml);
        $theHtml=str_replace("[Q","[",$theHtml);
        $dompdf->loadHtml($theHtml,'UTF-8');
        // (Optional) Setup the paper size and orientation
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        ob_end_clean();
        $handle = fopen($tmpfname, "w");
        fwrite($handle, $dompdf->output());
        fclose($handle);
        
        return $tmpfname;
    } 

    public function printHtmlPageToTempFilename($theHtmlText2BePrinted){
        $AA=$_SERVER["DOCUMENT_ROOT"];
        $tr=substr($AA,0,strrpos($AA,"/")).$_ENV['tempdir'];
        $tmpfname = tempnam($tr, "F302");
        unlink($tmpfname);
        $tmpfname.= ".pdf";
        
        $options = new Options();
        $options->set('defaultMediaType', 'all');
        $options->set('isFontSubsettingEnabled', true);
        $options->set('tempdir', $tr);
        $options->set('isPhpEnabled', true);
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isRemoteEnabled', true);   

        $dompdf = new Dompdf($options);

        $dompdf->loadHtml($theHtmlText2BePrinted,'UTF-8');
        // (Optional) Setup the paper size and orientation
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        ob_end_clean();
        $handle = fopen($tmpfname, "w");
        fwrite($handle, $dompdf->output());
        fclose($handle);
        return $tmpfname;
    }

    public function pippo($html){
        $tr=$_ENV['tempdir'];
        $tmpfname = tempnam($tr, "F285");
        $tmpfname.= ".pdf";

        $dompdf = new Dompdf();
        $dompdf->set_paper(array(0,0,700,600));

        $html=str_replace ('style="border: 0; margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; min-width: 100%; width: 100%;"',
        'style="border: 0; margin: 0; padding: 0; -webkit-text-size-adjust: 95%; -ms-text-size-adjust: 95%; min-width: 95%; width: 95%;"',
        $html);
        

        $html=str_replace ('min-width: 100% !important',
        'min-width: 95% !important',
        $html);
        $html=str_replace ('width: 100% !important',
        'width: 95% !important',
        $html);

        $html=str_replace ('width="100%"',
        'width="95%"',
        $html);
        $html=str_replace ('width: 100%',
        'width: 95%',
        $html);
        $html=str_replace ('height="100%"',
        'height="95%"',
        $html);
        $html=str_replace ('height: 100%',
        'height: 95%',
        $html);

        $html=str_replace ('width:100%','width:95%', $html);
        $html=str_replace ('height:100%','height:95%',$html);

/*
        $GLOBALS['bodyHeight'] = 0;

        $dompdf->setCallbacks(
        array(
            'myCallbacks' => array(
            'event' => 'end_frame', 'f' => function ($infos) {
                $frame = $infos["frame"];
                if (strtolower($frame->get_node()->nodeName) === "body") {
                    $padding_box = $frame->get_padding_box();
                    $GLOBALS['bodyHeight'] += $padding_box['h'];
                }
            }
            )
        )
        );

        $dompdf->loadHtml($html);
        $dompdf->render();
        unset($dompdf);

        $dompdf = new Dompdf();
        $dompdf->set_paper(array(0,0,600,$GLOBALS['bodyHeight']+50));
*/
        $dompdf->loadHtml($html);
        $dompdf->render();
        ob_end_clean();
        $handle = fopen($tmpfname, "w");
        fwrite($handle, $dompdf->output());
        fclose($handle);
        return $tmpfname;
    }






/*
    function test(){
        $startDate=wofoEnv->getNow("IT");
        $pdfHeader=$companyName."\r\n{b}Iscrizione ".$denomUser." ".$userName."{/b} - ".$startDate;
        $title=$companyName." - ".$siteName;
        // Stampa PDF
        $righe="{t}Richiesta di {b}iscrizione al corso{/b}{/t}{b}".$courseTitle." {i}".$courseWhen."{/i}{/b}{hr}{b}CONTRAENTE:{/b}\r\nCodice Cliente (da usare per i pagamenti):{b}".$userCODE."{/b}\r\n{b}".$denomUser." ".$userName."{/b}{i} (".$userSpec."){/i}\r\ne-mail:".$userEmail."\r\nTel.:".$userPhone."\r\n".$userAddress." - ".$userCap." ".$userCitta."\r\nCarta identità (num, luogo, scadenza):{b}".$userCID."{/b}\r\nCodice fiscale:{b}".$userCodFisc."{/b}{hr}{b}Fatturazione{/b}\r\n".$fattDenom."\r\n".$fattAddr." - ".$fattCAP." ".$fattCitta."\r\nPI/CF:{b}".$fattAccCode."{/b}\r\nSDI/PEC:{b}".$fattSDI."{/b}{hr}Inviato il: {b}".$msgDate."{/b}\r\n{hr}\r\n";
        $righe.="In seguito alla sottoscrizione del presente contratto, il Contraente acquista, per sé o per persona da nominare, ".$courseHours." di corso. Il contratto è perfezionato nel momento in cui ".$companyName." riceverà la presente debitamente compilata in ogni sua parte.{hr}{t}CONDIZIONI E PRIVACY{/t}1) Condizioni.{pl1}La sottoscrizione del presente modulo obbliga al versamento della quota di partecipazione, nei termini indicati nel presente contratto. Il mancato versamento della quota da parte del Contraente integrerà inadempimento contrattuale ed impedirà la partecipazione al corso; tuttavia, il contratto rimarrà perfettamente valido e vincolante tra le parti. La quota comprende il materiale didattico ed è riservata esclusivamente dagli iscritti al corso, essendone vietata la divulgazione e/o diffusione a terzi. Al termine del corso ai partecipanti che avranno seguito almeno il 90% delle lezioni verrà rilasciato l’attestato di partecipazione. L'Azienda ".$companyName." si impegna a organizzare e svolgere il corso come da contratto e da nota informativa ricevuta unitamente allo stesso e che si intende visionata ed espressamente approvata dal contraente. {/pl1}2) Validità.{pl1}L’iscrizione al corso è stata dal contraente perfezionata con la firma del presente contratto ed è vincolante a tutti gli effetti di legge. Con la sottoscrizione il Contraente si impegna a corrispondere integralmente il prezzo pattuito. {/pl1}3) Foro competente.{pl1}Per qualsiasi controversia le parti dichiarano che il Foro competente sarà quello di ".$foroCompetente.", fermo restando la competenza esclusiva del Foro del consumatore in tutti i casi in cui sarà applicabile alla fattispecie, avendo il Contraente tale qualifica. {/pl1}4) Recesso.{pl1}Il Contraente potrà liberamente recedere entro 10 giorni dalla sottoscrizione del presente contratto. Tale comunicazione potrà essere effettuata, entro lo stesso termine, tramite e-mail all'indirizzo {b}".$remoteStaffEmail."{/b} In ogni caso il recesso non potrà essere esercitato nel caso in cui la prestazione abbia avuto inizio. L’esecuzione del presente contratto avviene nel rispetto della normativa di cui al D. Lgs. 206/05, in quanto applicabile.{/pl1}5) Utilizzo del materiale didattico (slides, materiale audio e video).{pl1}{b}E’ fatto espresso divieto al Contraente di effettuare qualsiasi forma di riproduzione, divulgazione, commercializzazione ed utilizzazione del materiale didattico fornito da ".$companyName." al di fuori dell’uso strettamente connesso al presente contratto, ovverosia ai fini didattici legati al proprio personale apprendimento; il Contraente si accolla tutte le responsabilità di un eventuale uso indebito.{/b}{/pl1}\r\nCON LA PRESENTE ISCRIZIONE SI DICHIARA DI ESSERE IN POSSESSO DEI REQUISITI NECESSARI PER PARTECIPARE AL CORSO E SI ESONERA ".$companyName." DA OGNI RESPONSABILITA’. AI SENSI DEGLI ART. 1341 E 1342 C.C., DICHIARO DI AVERE LETTO, APPROVATO E ACCETTATO SPECIFICATAMENTE TUTTE LE SUPERIORI CONDIZIONI CONTRATTUALI CHE CONFERMO ESSERMI STATE ESPLICATE IN MANIERA SPECIFICA E CONFERMO DI AVER COMPRESO APPIENO.\r\n{hr}{pl2}{b}{i}firma applicata elettronicamente da ".$denomUser." ".$userName.":{/b}{/i}{/pl2}{pl3}".$acctMsg1."{/pl3}{hr}\r\n{i}Ai sensi dell’art. 13 del Regolamento UE 679/2016 (di seguito GDPR), Metabolicamente S.r.l., in qualità di Contitolare del trattamento dati, La informa che: i dati da Lei forniti saranno trattati per finalità di gestione amministrativa e logistica dei corsi stessi nonché per adempiere a obblighi di legge di natura fisica, contabile e amministrativa e per l’eventuale tutela dei diritti delle Contitolari, correlati alla esecuzione dei contratti; Il conferimento dei dati sopraindicati è necessario ai fini dell’iscrizione, pertanto, l’eventuale rifiuto a fornirli comporterà l’impossibilità di procedere all’iscrizione. Tale necessità rappresenta la base giuridica che legittima i conseguenti trattamenti. I dati saranno trattati con modalità cartacee e/o informatizzate. Nel rispetto dei principi di proporzionalità e necessità, i dati non saranno conservati per periodi più lunghi rispetto a quelli indispensabili alla realizzazione delle finalità sopra indicate e dunque al servizio offerto o alle specifiche norme di legge, successivamente saranno cancellati con modalità sicura. Nel rispetto delle misure di sicurezza adeguate i Suoi dati potranno essere comunicati ad altri soggetti pubblici e privati per l’adempimento di obblighi previsti dalla legge. Verranno comunicati al personale della Società Metabolicamente Srl per attività connesse all’organizzazione dell’evento. In nessun caso i dati saranno diffusi. In ogni momento Lei potrà esercitare i diritti ai sensi dell’art. 15 e seguenti del GDPR. Potrà ottenere la conferma dell’esistenza dei Suoi dati personali e chiederne la loro comunicazione in forma intelligibile. Avrà diritto di ottenere l’accesso, l’aggiornamento, la rettificazione, l’integrazione e la cancellazione dei dati o la limitazione del trattamento rivolgendosi ai Contitolari del trattamento: Metabolicamente srl. Lei ha, infine, diritto di proporre reclamo ovvero effettuare una segnalazione al Garante per la Protezione dei Dati Personali oppure in alternativa presentare ricorso all’Autorità Giudiziaria. I contatti del Garante per la Protezione dei Dati Personali sono consultabili sul sito web http://www.garanteprivacy.it {/i}\r\n{hr}{pl2}{b}{i}firma applicata elettronicamente da ".$denomUser." ".$userName.":{/b}{/i}{/pl2}{pl3}".$acctMsg2."{/pl3}{hr}\r\n{i}Letta l’Informativa fornitami ai sensi dell’art. 13 del GDPR autorizzo Metabolicamente srl all’invio, tramite sistemi automatizzati, quali e-mail o sms, di comunicazioni commerciali, pubblicitarie e promozionali e ad attività di profilazione al fine di potermi fornire promozioni personalizzate riservate ai clienti della Società, ovvero di società controllate, affiliate o comunque collegate. {/i}\r\n{hr}{pl2}{b}{i}firma applicata elettronicamente da ".$denomUser." ".$userName.":{/b}{/i}{/pl2}{pl3}".$acctMsg3."{/pl3}";
    }
    */
}